In [1]:
# Importe a biblioteca numpy como "np"
import numpy as np

In [3]:
# Exercício 1 - Crie um array com a lista abaixo e imprima na tela o array e o type
python_list = [1, 2, 3]
array = np.array(python_list)
print(array)
print(type(array))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
# Exercício 2 - Imprima na tela a dimensão do array acima
array.ndim

1

In [6]:
# Exercício 3 - Crie um array 3x3 só com zeros
array_3d = np.zeros((3, 3))
array_3d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# Exercício 4 - Crie uma sequência numérica que vai de 2 até 15
sequence = np.arange(2, 16)
sequence

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])